sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - RUSTFLAGS=-Dwarnings cargo build && cargo test
  - cargo fmt --all -- --check
