sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - nightly
before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - type -p cargo-install-update || cargo install --force cargo-update
  - cargo install-update -i rustfmt-nightly
script:
  - RUSTFLAGS=-Dwarnings cargo build && cargo test
  - cargo fmt -- --check
