[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
futures = "*"
futures-await = "*"
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"
tokio-rustls = "*"
tokio-service = "*"
net2 = "*"

acme-client = { version = "*", default-features = false }

base64 = "*"

byteorder = "*"

chrono = "*"

structopt = "*"
structopt-derive = "*"

hex = "*"

hyper = ">=0.11"
hyper-rustls = ">=0.11"

openssl = ">=0.10"

ring = "0.13.0-alpha"

rustls = { version = ">=0.11", features = ["dangerous_configuration"] }

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

tera = ">=0.10.4"

url = "*"

webpki = "0.18.0-alpha"
