[package]
name = "ct-submitter"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
base64 = "*"

byteorder = "*"

hex = "*"

hyper = "*"
hyper-native-tls = "*"

rayon = "*"

ring = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

pem = "*"

prettytable-rs = "*"

url = "*"
