[package]
name = "ct-tools"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
futures = ">=0.3.1"
tokio = { version = ">=0.2.0", features = ["time", "macros", "tcp", "stream"] }

base64 = ">=0.10"

structopt = "*"
structopt-derive = "*"

hex = "*"

reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }

ring = "*"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

pem = "*"

prettytable-rs = "*"

url = "*"

